#
# Copyright (C) 2020 Google LLC
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

SUPPORTED_TAGS = [
    'J2_jump', 'J2_jumpr', 'J2_jumpt', 'J2_jumpf', 'J2_jumptpt', 'J2_jumpfpt',
    'J2_jumprt', 'J2_jumprf', 'J2_jumprtpt', 'J2_jumprfpt', 'J2_jumptnew',
    'J2_jumpfnew', 'J2_jumptnewpt', 'J2_jumpfnewpt', 'J2_jumprtnew',
    'J2_jumprfnew', 'J2_jumprtnewpt', 'J2_jumprfnewpt', 'J2_jumprz',
    'J2_jumprnz', 'J2_jumprzpt', 'J2_jumprnzpt', 'J2_jumprgtez',
    'J2_jumprgtezpt', 'J2_jumprltez', 'J2_jumprltezpt', 'J4_cmpeqi_tp0_jump_nt',
    'J4_cmpeqi_fp0_jump_nt', 'J4_cmpeqi_tp0_jump_t', 'J4_cmpeqi_fp0_jump_t',
    'J4_cmpeqi_tp1_jump_nt', 'J4_cmpeqi_fp1_jump_nt', 'J4_cmpeqi_tp1_jump_t',
    'J4_cmpeqi_fp1_jump_t', 'J4_cmpgti_tp0_jump_nt', 'J4_cmpgti_fp0_jump_nt',
    'J4_cmpgti_tp0_jump_t', 'J4_cmpgti_fp0_jump_t', 'J4_cmpgti_tp1_jump_nt',
    'J4_cmpgti_fp1_jump_nt', 'J4_cmpgti_tp1_jump_t', 'J4_cmpgti_fp1_jump_t',
    'J4_cmpgtui_tp0_jump_nt', 'J4_cmpgtui_fp0_jump_nt', 'J4_cmpgtui_tp0_jump_t',
    'J4_cmpgtui_fp0_jump_t', 'J4_cmpgtui_tp1_jump_nt', 'J4_cmpgtui_fp1_jump_nt',
    'J4_cmpgtui_tp1_jump_t', 'J4_cmpgtui_fp1_jump_t', 'J4_cmpeqn1_tp0_jump_nt',
    'J4_cmpeqn1_fp0_jump_nt', 'J4_cmpeqn1_tp0_jump_t', 'J4_cmpeqn1_fp0_jump_t',
    'J4_cmpeqn1_tp1_jump_nt', 'J4_cmpeqn1_fp1_jump_nt', 'J4_cmpeqn1_tp1_jump_t',
    'J4_cmpeqn1_fp1_jump_t', 'J4_cmpgtn1_tp0_jump_nt', 'J4_cmpgtn1_fp0_jump_nt',
    'J4_cmpgtn1_tp0_jump_t', 'J4_cmpgtn1_fp0_jump_t', 'J4_cmpgtn1_tp1_jump_nt',
    'J4_cmpgtn1_fp1_jump_nt', 'J4_cmpgtn1_tp1_jump_t', 'J4_cmpgtn1_fp1_jump_t',
    'J4_tstbit0_tp0_jump_nt', 'J4_tstbit0_fp0_jump_nt', 'J4_tstbit0_tp0_jump_t',
    'J4_tstbit0_fp0_jump_t', 'J4_tstbit0_tp1_jump_nt', 'J4_tstbit0_fp1_jump_nt',
    'J4_tstbit0_tp1_jump_t', 'J4_tstbit0_fp1_jump_t', 'J4_cmpeq_tp0_jump_nt',
    'J4_cmpeq_fp0_jump_nt', 'J4_cmpeq_tp0_jump_t', 'J4_cmpeq_fp0_jump_t',
    'J4_cmpeq_tp1_jump_nt', 'J4_cmpeq_fp1_jump_nt', 'J4_cmpeq_tp1_jump_t',
    'J4_cmpeq_fp1_jump_t', 'J4_cmpgt_tp0_jump_nt', 'J4_cmpgt_fp0_jump_nt',
    'J4_cmpgt_tp0_jump_t', 'J4_cmpgt_fp0_jump_t', 'J4_cmpgt_tp1_jump_nt',
    'J4_cmpgt_fp1_jump_nt', 'J4_cmpgt_tp1_jump_t', 'J4_cmpgt_fp1_jump_t',
    'J4_cmpgtu_tp0_jump_nt', 'J4_cmpgtu_fp0_jump_nt', 'J4_cmpgtu_tp0_jump_t',
    'J4_cmpgtu_fp0_jump_t', 'J4_cmpgtu_tp1_jump_nt', 'J4_cmpgtu_fp1_jump_nt',
    'J4_cmpgtu_tp1_jump_t', 'J4_cmpgtu_fp1_jump_t', 'J4_jumpseti',
    'J4_jumpsetr', 'J4_cmpeqi_t_jumpnv_t', 'J4_cmpeqi_t_jumpnv_nt',
    'J4_cmpeqi_f_jumpnv_t', 'J4_cmpeqi_f_jumpnv_nt', 'J4_cmpgti_t_jumpnv_t',
    'J4_cmpgti_t_jumpnv_nt', 'J4_cmpgti_f_jumpnv_t', 'J4_cmpgti_f_jumpnv_nt',
    'J4_cmpgtui_t_jumpnv_t', 'J4_cmpgtui_t_jumpnv_nt', 'J4_cmpgtui_f_jumpnv_t',
    'J4_cmpgtui_f_jumpnv_nt', 'J4_cmpeqn1_t_jumpnv_t', 'J4_cmpeqn1_t_jumpnv_nt',
    'J4_cmpeqn1_f_jumpnv_t', 'J4_cmpeqn1_f_jumpnv_nt', 'J4_cmpgtn1_t_jumpnv_t',
    'J4_cmpgtn1_t_jumpnv_nt', 'J4_cmpgtn1_f_jumpnv_t', 'J4_cmpgtn1_f_jumpnv_nt',
    'J4_tstbit0_t_jumpnv_t', 'J4_tstbit0_t_jumpnv_nt', 'J4_tstbit0_f_jumpnv_t',
    'J4_tstbit0_f_jumpnv_nt', 'J4_cmpeq_t_jumpnv_t', 'J4_cmpeq_t_jumpnv_nt',
    'J4_cmpgt_t_jumpnv_t', 'J4_cmpgt_t_jumpnv_nt', 'J4_cmpgtu_t_jumpnv_t',
    'J4_cmpgtu_t_jumpnv_nt', 'J4_cmplt_t_jumpnv_t', 'J4_cmplt_t_jumpnv_nt',
    'J4_cmpltu_t_jumpnv_t', 'J4_cmpltu_t_jumpnv_nt', 'J4_cmpeq_f_jumpnv_t',
    'J4_cmpeq_f_jumpnv_nt', 'J4_cmpgt_f_jumpnv_t', 'J4_cmpgt_f_jumpnv_nt',
    'J4_cmpgtu_f_jumpnv_t', 'J4_cmpgtu_f_jumpnv_nt', 'J4_cmplt_f_jumpnv_t',
    'J4_cmplt_f_jumpnv_nt', 'J4_cmpltu_f_jumpnv_t', 'J4_cmpltu_f_jumpnv_nt',
    'J2_call', 'J2_callt', 'J2_callf', 'J2_callr', 'J2_callrt', 'J2_callrf',
    'J2_loop0r', 'J2_loop1r', 'J2_loop0i', 'J2_loop1i', 'J2_ploop1sr',
    'J2_ploop1si', 'J2_ploop2sr', 'J2_ploop2si', 'J2_ploop3sr', 'J2_ploop3si',
    'J2_endloop01', 'J2_endloop0', 'J2_endloop1', 'L2_loadrub_io',
    'L4_loadrub_ur', 'L4_loadrub_ap', 'L2_loadrub_pi', 'L2_loadrb_io',
    'L4_loadrb_ur', 'L4_loadrb_ap', 'L2_loadrb_pi', 'L2_loadruh_io',
    'L4_loadruh_ur', 'L4_loadruh_ap', 'L2_loadruh_pi', 'L2_loadrh_io',
    'L4_loadrh_ur', 'L4_loadrh_ap', 'L2_loadrh_pi', 'L2_loadri_io',
    'L4_loadri_ur', 'L4_loadri_ap', 'L2_loadri_pi', 'L2_loadrd_io',
    'L4_loadrd_ur', 'L4_loadrd_ap', 'L2_loadrd_pi', 'S2_storerb_io',
    'S2_storerb_pi', 'S4_storerb_ap', 'S4_storerb_ur', 'S2_storerh_io',
    'S2_storerh_pi', 'S4_storerh_ap', 'S4_storerh_ur', 'S2_storerf_io',
    'S2_storerf_pi', 'S4_storerf_ap', 'S4_storerf_ur', 'S2_storeri_io',
    'S2_storeri_pi', 'S4_storeri_ap', 'S4_storeri_ur', 'S2_storerd_io',
    'S2_storerd_pi', 'S4_storerd_ap', 'S4_storerd_ur', 'S2_storerinew_io',
    'S2_storerinew_pi', 'S4_storerinew_ap', 'S4_storerinew_ur',
    'S2_storerbnew_io', 'S2_storerbnew_pi', 'S4_storerbnew_ap',
    'S4_storerbnew_ur', 'S2_storerhnew_io', 'S2_storerhnew_pi',
    'S4_storerhnew_ap', 'S4_storerhnew_ur', 'S2_allocframe', 'L2_deallocframe',
    'L4_return', 'L4_return_t', 'L4_return_f', 'L4_return_tnew_pt',
    'L4_return_fnew_pt', 'L4_return_tnew_pnt', 'L4_return_fnew_pnt',
    'L2_loadw_locked', 'S2_storew_locked', 'L4_loadd_locked',
    'S4_stored_locked', 'L4_loadrub_rr', 'L2_ploadrubt_io', 'L2_ploadrubt_pi',
    'L2_ploadrubf_io', 'L2_ploadrubf_pi', 'L2_ploadrubtnew_io',
    'L2_ploadrubfnew_io', 'L4_ploadrubt_rr', 'L4_ploadrubf_rr',
    'L4_ploadrubtnew_rr', 'L4_ploadrubfnew_rr', 'L2_ploadrubtnew_pi',
    'L2_ploadrubfnew_pi', 'L4_ploadrubt_abs', 'L4_ploadrubf_abs',
    'L4_ploadrubtnew_abs', 'L4_ploadrubfnew_abs', 'L4_loadrb_rr',
    'L2_ploadrbt_io', 'L2_ploadrbt_pi', 'L2_ploadrbf_io', 'L2_ploadrbf_pi',
    'L2_ploadrbtnew_io', 'L2_ploadrbfnew_io', 'L4_ploadrbt_rr',
    'L4_ploadrbf_rr', 'L4_ploadrbtnew_rr', 'L4_ploadrbfnew_rr',
    'L2_ploadrbtnew_pi', 'L2_ploadrbfnew_pi', 'L4_ploadrbt_abs',
    'L4_ploadrbf_abs', 'L4_ploadrbtnew_abs', 'L4_ploadrbfnew_abs',
    'L4_loadruh_rr', 'L2_ploadruht_io', 'L2_ploadruht_pi', 'L2_ploadruhf_io',
    'L2_ploadruhf_pi', 'L2_ploadruhtnew_io', 'L2_ploadruhfnew_io',
    'L4_ploadruht_rr', 'L4_ploadruhf_rr', 'L4_ploadruhtnew_rr',
    'L4_ploadruhfnew_rr', 'L2_ploadruhtnew_pi', 'L2_ploadruhfnew_pi',
    'L4_ploadruht_abs', 'L4_ploadruhf_abs', 'L4_ploadruhtnew_abs',
    'L4_ploadruhfnew_abs', 'L4_loadrh_rr', 'L2_ploadrht_io', 'L2_ploadrht_pi',
    'L2_ploadrhf_io', 'L2_ploadrhf_pi', 'L2_ploadrhtnew_io',
    'L2_ploadrhfnew_io', 'L4_ploadrht_rr', 'L4_ploadrhf_rr',
    'L4_ploadrhtnew_rr', 'L4_ploadrhfnew_rr', 'L2_ploadrhtnew_pi',
    'L2_ploadrhfnew_pi', 'L4_ploadrht_abs', 'L4_ploadrhf_abs',
    'L4_ploadrhtnew_abs', 'L4_ploadrhfnew_abs', 'L4_loadri_rr',
    'L2_ploadrit_io', 'L2_ploadrit_pi', 'L2_ploadrif_io', 'L2_ploadrif_pi',
    'L2_ploadritnew_io', 'L2_ploadrifnew_io', 'L4_ploadrit_rr',
    'L4_ploadrif_rr', 'L4_ploadritnew_rr', 'L4_ploadrifnew_rr',
    'L2_ploadritnew_pi', 'L2_ploadrifnew_pi', 'L4_ploadrit_abs',
    'L4_ploadrif_abs', 'L4_ploadritnew_abs', 'L4_ploadrifnew_abs',
    'L4_loadrd_rr', 'L2_ploadrdt_io', 'L2_ploadrdt_pi', 'L2_ploadrdf_io',
    'L2_ploadrdf_pi', 'L2_ploadrdtnew_io', 'L2_ploadrdfnew_io',
    'L4_ploadrdt_rr', 'L4_ploadrdf_rr', 'L4_ploadrdtnew_rr',
    'L4_ploadrdfnew_rr', 'L2_ploadrdtnew_pi', 'L2_ploadrdfnew_pi',
    'L4_ploadrdt_abs', 'L4_ploadrdf_abs', 'L4_ploadrdtnew_abs',
    'L4_ploadrdfnew_abs', 'S4_storerb_rr', 'S2_pstorerbt_io', 'S2_pstorerbt_pi',
    'S2_pstorerbf_io', 'S2_pstorerbf_pi', 'S4_pstorerbt_rr', 'S4_pstorerbf_rr',
    'S4_pstorerbtnew_io', 'S4_pstorerbfnew_io', 'S4_pstorerbtnew_rr',
    'S4_pstorerbfnew_rr', 'S2_pstorerbtnew_pi', 'S2_pstorerbfnew_pi',
    'S4_pstorerbt_abs', 'S4_pstorerbf_abs', 'S4_pstorerbtnew_abs',
    'S4_pstorerbfnew_abs', 'S4_storerh_rr', 'S2_pstorerht_io',
    'S2_pstorerht_pi', 'S2_pstorerhf_io', 'S2_pstorerhf_pi', 'S4_pstorerht_rr',
    'S4_pstorerhf_rr', 'S4_pstorerhtnew_io', 'S4_pstorerhfnew_io',
    'S4_pstorerhtnew_rr', 'S4_pstorerhfnew_rr', 'S2_pstorerhtnew_pi',
    'S2_pstorerhfnew_pi', 'S4_pstorerht_abs', 'S4_pstorerhf_abs',
    'S4_pstorerhtnew_abs', 'S4_pstorerhfnew_abs', 'S4_storerf_rr',
    'S2_pstorerft_io', 'S2_pstorerft_pi', 'S2_pstorerff_io', 'S2_pstorerff_pi',
    'S4_pstorerft_rr', 'S4_pstorerff_rr', 'S4_pstorerftnew_io',
    'S4_pstorerffnew_io', 'S4_pstorerftnew_rr', 'S4_pstorerffnew_rr',
    'S2_pstorerftnew_pi', 'S2_pstorerffnew_pi', 'S4_pstorerft_abs',
    'S4_pstorerff_abs', 'S4_pstorerftnew_abs', 'S4_pstorerffnew_abs',
    'S4_storeri_rr', 'S2_pstorerit_io', 'S2_pstorerit_pi', 'S2_pstorerif_io',
    'S2_pstorerif_pi', 'S4_pstorerit_rr', 'S4_pstorerif_rr',
    'S4_pstoreritnew_io', 'S4_pstorerifnew_io', 'S4_pstoreritnew_rr',
    'S4_pstorerifnew_rr', 'S2_pstoreritnew_pi', 'S2_pstorerifnew_pi',
    'S4_pstorerit_abs', 'S4_pstorerif_abs', 'S4_pstoreritnew_abs',
    'S4_pstorerifnew_abs', 'S4_storerd_rr', 'S2_pstorerdt_io',
    'S2_pstorerdt_pi', 'S2_pstorerdf_io', 'S2_pstorerdf_pi', 'S4_pstorerdt_rr',
    'S4_pstorerdf_rr', 'S4_pstorerdtnew_io', 'S4_pstorerdfnew_io',
    'S4_pstorerdtnew_rr', 'S4_pstorerdfnew_rr', 'S2_pstorerdtnew_pi',
    'S2_pstorerdfnew_pi', 'S4_pstorerdt_abs', 'S4_pstorerdf_abs',
    'S4_pstorerdtnew_abs', 'S4_pstorerdfnew_abs', 'S4_storerinew_rr',
    'S2_pstorerinewt_io', 'S2_pstorerinewt_pi', 'S2_pstorerinewf_io',
    'S2_pstorerinewf_pi', 'S4_pstorerinewt_rr', 'S4_pstorerinewf_rr',
    'S4_pstorerinewtnew_io', 'S4_pstorerinewfnew_io', 'S4_pstorerinewtnew_rr',
    'S4_pstorerinewfnew_rr', 'S2_pstorerinewtnew_pi', 'S2_pstorerinewfnew_pi',
    'S4_pstorerinewt_abs', 'S4_pstorerinewf_abs', 'S4_pstorerinewtnew_abs',
    'S4_pstorerinewfnew_abs', 'S4_storerbnew_rr', 'S2_pstorerbnewt_io',
    'S2_pstorerbnewt_pi', 'S2_pstorerbnewf_io', 'S2_pstorerbnewf_pi',
    'S4_pstorerbnewt_rr', 'S4_pstorerbnewf_rr', 'S4_pstorerbnewtnew_io',
    'S4_pstorerbnewfnew_io', 'S4_pstorerbnewtnew_rr', 'S4_pstorerbnewfnew_rr',
    'S2_pstorerbnewtnew_pi', 'S2_pstorerbnewfnew_pi', 'S4_pstorerbnewt_abs',
    'S4_pstorerbnewf_abs', 'S4_pstorerbnewtnew_abs', 'S4_pstorerbnewfnew_abs',
    'S4_storerhnew_rr', 'S2_pstorerhnewt_io', 'S2_pstorerhnewt_pi',
    'S2_pstorerhnewf_io', 'S2_pstorerhnewf_pi', 'S4_pstorerhnewt_rr',
    'S4_pstorerhnewf_rr', 'S4_pstorerhnewtnew_io', 'S4_pstorerhnewfnew_io',
    'S4_pstorerhnewtnew_rr', 'S4_pstorerhnewfnew_rr', 'S2_pstorerhnewtnew_pi',
    'S2_pstorerhnewfnew_pi', 'S4_pstorerhnewt_abs', 'S4_pstorerhnewf_abs',
    'S4_pstorerhnewtnew_abs', 'S4_pstorerhnewfnew_abs', 'L4_add_memopw_io',
    'L4_add_memopb_io', 'L4_add_memoph_io', 'L4_sub_memopw_io',
    'L4_sub_memopb_io', 'L4_sub_memoph_io', 'L4_and_memopw_io',
    'L4_and_memopb_io', 'L4_and_memoph_io', 'L4_or_memopw_io',
    'L4_or_memopb_io', 'L4_or_memoph_io', 'L4_iadd_memopw_io',
    'L4_iadd_memopb_io', 'L4_iadd_memoph_io', 'L4_isub_memopw_io',
    'L4_isub_memopb_io', 'L4_isub_memoph_io', 'L4_iand_memopw_io',
    'L4_iand_memopb_io', 'L4_iand_memoph_io', 'L4_ior_memopw_io',
    'L4_ior_memopb_io', 'L4_ior_memoph_io', 'S4_storeirbt_io',
    'S4_storeirbf_io', 'S4_storeirbtnew_io', 'S4_storeirbfnew_io',
    'S4_storeirht_io', 'S4_storeirhf_io', 'S4_storeirhtnew_io',
    'S4_storeirhfnew_io', 'S4_storeirit_io', 'S4_storeirif_io',
    'S4_storeiritnew_io', 'S4_storeirifnew_io', 'S4_storeirb_io',
    'S4_storeirh_io', 'S4_storeiri_io', 'L2_loadrubgp', 'L2_loadrbgp',
    'L2_loadruhgp', 'L2_loadrhgp', 'L2_loadrigp', 'L2_loadrdgp', 'S2_storerbgp',
    'S2_storerhgp', 'S2_storerfgp', 'S2_storerigp', 'S2_storerdgp',
    'S2_storerinewgp', 'S2_storerbnewgp', 'S2_storerhnewgp', 'C2_cmpeq',
    'C2_cmpgt', 'C2_cmpgtu', 'C2_cmpeqp', 'C2_cmpgtp', 'C2_cmpgtup',
    'A4_rcmpeqi', 'A4_rcmpneqi', 'A4_rcmpeq', 'A4_rcmpneq', 'C2_bitsset',
    'C2_bitsclr', 'C4_nbitsset', 'C4_nbitsclr', 'C2_cmpeqi', 'C2_cmpgti',
    'C2_cmpgtui', 'C2_bitsclri', 'C4_nbitsclri', 'C4_cmpneqi', 'C4_cmpltei',
    'C4_cmplteui', 'C4_cmpneq', 'C4_cmplte', 'C4_cmplteu', 'C2_and', 'C2_or',
    'C2_xor', 'C2_andn', 'C2_not', 'C2_orn', 'C4_and_and', 'C4_and_or',
    'C4_or_and', 'C4_or_or', 'C4_and_andn', 'C4_and_orn', 'C4_or_andn',
    'C4_or_orn', 'C2_all8', 'C2_vitpack', 'C2_mux', 'C2_cmovenewit',
    'C2_cmovenewif', 'C2_cmoveit', 'C2_cmoveif', 'C2_ccombinewnewt',
    'C2_ccombinewnewf', 'C2_ccombinewt', 'C2_ccombinewf', 'C2_muxii',
    'C2_muxir', 'C2_muxri', 'A4_cmpbeq', 'A4_cmpbeqi', 'A4_cmpbgtu',
    'A4_cmpbgtui', 'A4_cmpbgt', 'A4_cmpbgti', 'A4_cmpheq', 'A4_cmphgt',
    'A4_cmphgtu', 'A4_cmpheqi', 'A4_cmphgti', 'A4_cmphgtui', 'C2_tfrpr',
    'C2_tfrrp', 'M2_mpysip', 'M2_mpysin', 'M2_macsip', 'M2_macsin',
    'M2_dpmpyss_s0', 'M2_dpmpyss_acc_s0', 'M2_dpmpyss_nac_s0', 'M2_dpmpyuu_s0',
    'M2_dpmpyuu_acc_s0', 'M2_dpmpyuu_nac_s0', 'M2_mpy_up', 'M2_mpy_up_s1',
    'M2_mpyu_up', 'M2_mpysu_up', 'M2_dpmpyss_rnd_s0', 'M2_mpyi', 'M2_maci',
    'M2_mnaci', 'M2_acci', 'M2_accii', 'M2_nacci', 'M2_naccii', 'M2_subacc',
    'M4_mpyrr_addr', 'M4_mpyri_addr_u2', 'M4_mpyri_addr', 'M4_mpyri_addi',
    'M4_mpyrr_addi', 'M7_dcmpyrw', 'M7_dcmpyrw_acc', 'M7_dcmpyrwc',
    'M7_dcmpyrwc_acc', 'M7_dcmpyiw', 'M7_dcmpyiw_acc', 'M7_dcmpyiwc',
    'M7_dcmpyiwc_acc', 'A2_add', 'A2_sub', 'A2_paddt', 'A2_paddf',
    'A2_paddtnew', 'A2_paddfnew', 'A2_psubt', 'A2_psubf', 'A2_psubtnew',
    'A2_psubfnew', 'A2_paddit', 'A2_paddif', 'A2_padditnew', 'A2_paddifnew',
    'A2_pxort', 'A2_pxorf', 'A2_pxortnew', 'A2_pxorfnew', 'A2_pandt',
    'A2_pandf', 'A2_pandtnew', 'A2_pandfnew', 'A2_port', 'A2_porf',
    'A2_portnew', 'A2_porfnew', 'A4_psxtbt', 'A4_psxtbf', 'A4_psxtbtnew',
    'A4_psxtbfnew', 'A4_pzxtbt', 'A4_pzxtbf', 'A4_pzxtbtnew', 'A4_pzxtbfnew',
    'A4_psxtht', 'A4_psxthf', 'A4_psxthtnew', 'A4_psxthfnew', 'A4_pzxtht',
    'A4_pzxthf', 'A4_pzxthtnew', 'A4_pzxthfnew', 'A4_paslht', 'A4_paslhf',
    'A4_paslhtnew', 'A4_paslhfnew', 'A4_pasrht', 'A4_pasrhf', 'A4_pasrhtnew',
    'A4_pasrhfnew', 'A2_addi', 'C4_addipc', 'A2_addh_l16_ll', 'A2_addh_l16_hl',
    'A2_subh_l16_ll', 'A2_subh_l16_hl', 'A2_addh_h16_ll', 'A2_addh_h16_lh',
    'A2_addh_h16_hl', 'A2_addh_h16_hh', 'A2_subh_h16_ll', 'A2_subh_h16_lh',
    'A2_subh_h16_hl', 'A2_subh_h16_hh', 'A2_aslh', 'A2_asrh', 'A2_addp',
    'A2_addspl', 'A2_addsph', 'A2_subp', 'A2_abs', 'A2_negp', 'A2_absp',
    'A2_max', 'A2_maxu', 'A2_min', 'A2_minu', 'A2_maxp', 'A2_maxup', 'A2_minp',
    'A2_minup', 'A2_nop', 'A4_ext', 'A2_tfr', 'A2_tfrsi', 'A2_sxtb', 'A2_zxth',
    'A2_sxth', 'A2_combinew', 'A4_combineri', 'A4_combineir', 'A2_combineii',
    'A4_combineii', 'A2_combine_hh', 'A2_combine_hl', 'A2_combine_lh',
    'A2_combine_ll', 'A2_tfril', 'A2_tfrih', 'A2_tfrcrr', 'A2_tfrrcr',
    'A4_tfrcpp', 'A4_tfrpcp', 'A2_and', 'A2_or', 'A2_xor', 'M2_xor_xacc',
    'M4_xor_xacc', 'A4_andn', 'A4_orn', 'A4_andnp', 'A4_ornp', 'S4_addaddi',
    'S4_subaddi', 'M4_and_and', 'M4_and_andn', 'M4_and_or', 'M4_and_xor',
    'M4_or_and', 'M4_or_andn', 'M4_or_or', 'M4_or_xor', 'S4_or_andix',
    'S4_or_andi', 'S4_or_ori', 'M4_xor_and', 'M4_xor_or', 'M4_xor_andn',
    'A2_subri', 'A2_andir', 'A2_orir', 'A2_andp', 'A2_orp', 'A2_xorp',
    'A2_notp', 'A4_modwrapu', 'F2_sfimm_p', 'F2_sfimm_n', 'F2_dfmpylh',
    'S2_asr_i_r', 'S2_lsr_i_r', 'S2_asl_i_r', 'S6_rol_i_r', 'S2_asr_i_p',
    'S2_lsr_i_p', 'S2_asl_i_p', 'S6_rol_i_p', 'S2_asr_i_r_acc',
    'S2_lsr_i_r_acc', 'S2_asl_i_r_acc', 'S6_rol_i_r_acc', 'S2_asr_i_p_acc',
    'S2_lsr_i_p_acc', 'S2_asl_i_p_acc', 'S6_rol_i_p_acc', 'S2_asr_i_r_nac',
    'S2_lsr_i_r_nac', 'S2_asl_i_r_nac', 'S6_rol_i_r_nac', 'S2_asr_i_p_nac',
    'S2_lsr_i_p_nac', 'S2_asl_i_p_nac', 'S6_rol_i_p_nac', 'S2_lsr_i_r_xacc',
    'S2_asl_i_r_xacc', 'S6_rol_i_r_xacc', 'S2_lsr_i_p_xacc', 'S2_asl_i_p_xacc',
    'S6_rol_i_p_xacc', 'S2_asr_i_r_and', 'S2_lsr_i_r_and', 'S2_asl_i_r_and',
    'S6_rol_i_r_and', 'S2_asr_i_r_or', 'S2_lsr_i_r_or', 'S2_asl_i_r_or',
    'S6_rol_i_r_or', 'S2_asr_i_p_and', 'S2_lsr_i_p_and', 'S2_asl_i_p_and',
    'S6_rol_i_p_and', 'S2_asr_i_p_or', 'S2_lsr_i_p_or', 'S2_asl_i_p_or',
    'S6_rol_i_p_or', 'S2_addasl_rrri', 'S4_andi_asl_ri', 'S4_ori_asl_ri',
    'S4_addi_asl_ri', 'S4_subi_asl_ri', 'S2_valignib', 'S2_valignrb',
    'S2_vspliceib', 'S2_vsplicerb', 'S2_insert', 'A4_bitspliti', 'A4_bitsplit',
    'S4_extract', 'S2_extractu', 'S2_insertp', 'S4_extractp', 'S2_extractup',
    'S2_mask', 'S2_tstbit_i', 'S4_ntstbit_i', 'S2_setbit_i', 'S2_togglebit_i',
    'S2_clrbit_i', 'A2_swiz', 'J2_trap0', 'J2_pause', 'Y2_break', 'Y2_icinva',
    'Y2_isync', 'Y2_barrier', 'Y2_syncht', 'Y2_dcfetchbo', 'Y2_dccleana',
    'Y2_dccleaninva', 'Y2_dcinva', 'Y4_l2fetch', 'Y5_l2fetch', 'SA1_addi',
    'SA1_tfr', 'SA1_seti', 'SA1_setin1', 'SA1_clrtnew', 'SA1_clrfnew',
    'SA1_clrt', 'SA1_clrf', 'SA1_addsp', 'SA1_inc', 'SA1_dec', 'SA1_addrx',
    'SA1_zxtb', 'SA1_and1', 'SA1_sxtb', 'SA1_zxth', 'SA1_sxth', 'SA1_combinezr',
    'SA1_combinerz', 'SA1_combine0i', 'SA1_combine1i', 'SA1_combine2i',
    'SA1_combine3i', 'SA1_cmpeqi', 'SL1_loadri_io', 'SL1_loadrub_io',
    'SL2_loadrh_io', 'SL2_loadruh_io', 'SL2_loadrb_io', 'SL2_loadri_sp',
    'SL2_loadrd_sp', 'SL2_deallocframe', 'SL2_return', 'SL2_return_t',
    'SL2_return_f', 'SL2_return_tnew', 'SL2_return_fnew', 'SL2_jumpr31',
    'SL2_jumpr31_t', 'SL2_jumpr31_f', 'SL2_jumpr31_tnew', 'SL2_jumpr31_fnew',
    'SS1_storew_io', 'SS1_storeb_io', 'SS2_storeh_io', 'SS2_stored_sp',
    'SS2_storew_sp', 'SS2_storewi0', 'SS2_storebi0', 'SS2_storewi1',
    'SS2_storebi1', 'SS2_allocframe'
]
